global:
  scrape_interval: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "obesity_ml_model_exporter"

    static_configs:
      - targets: ["127.0.0.1:8001"]
        labels:
          app: "prometheus"
